(G-code generated by FlatCAM Evo vUnstable - Version Date: 2023/6/31)

(Name: Toolhead PCB-PTH.drl_cnc)
(Type: G-code from Excellon)
(Units: MM)

(Created on Friday, 10 October 2025 at 14:37)

(This preprocessor is the default preprocessor.)
(It is made to work with MACH3 compatible motion controllers.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 0.5)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 100.0)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -2.0)

(Tools Offset: )
(Tool: 1 -> Offset Z: 0.0)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 2.0)

(Z Start: None mm)
(Z End: 2.0 mm)
(X,Y End: None mm)
(Steps per circle: 16)
(Preprocessor Excellon: default)

(X range:    1.2490 ...   29.5000  mm)
(Y range:    1.0250 ...   24.3600  mm)

(Spindle Speed: 10000 RPM)
G21
G90
G94

G01 F100.00
G00 Z2.0000

M03 S10000
G4 P1
G00 X19.4000 Y1.4100
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X19.4000 Y3.4100
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X19.4000 Y5.4100
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X19.4000 Y7.4100
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X19.4000 Y9.4100
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X19.4000 Y11.4100
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X22.5800 Y11.4100
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X22.5800 Y9.4100
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X22.5800 Y7.4100
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X22.5800 Y5.4100
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X22.5800 Y3.4100
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X22.5800 Y1.4100
G01 Z-2.0000
G01 Z0
G00 Z2.0000
M05
G00 Z2.00


